### ISSUE TITLE
Listing all pages and associated routes

### ISSUE THREAD

**Issue by MarvinLeRouge** [MarvinLeRouge/simplimmo#20]

**Comment by MarsaColombo** [comment]
- [ ] Page d'acceuil
    Chemin: /
    Controller: Property
    Method: index

- [ ] Page de détail
   Chemin : /(maison|appartement)/nom-du-bien-sanitized-:id
   Controller : House / Appartment
   Method : getDetail(id)

- [ ] Page de demande de contact pour un bien
    Chemin: /call-me-back/:id
    controller: property
    method: callmeback(id)
  
- [ ] Page de demande de contact générique
   Chemin : /contact
   Controller : Générique
   Method : contact(body)

- [ ] Mentions légales 
   Chemin : /legal-mention
   Controller : Générique
   Method : getLegalMention()

- [ ] Page de favoris
   Chemin : /favorites
   Controller : Favorites
   Method : getFavorites(clientId)

**Comment by MarsaColombo** [comment]
Page de dashboard : 
Chemin : /dashboard

- [ ] Page de login métier
   Chemin : /login
   Controller : Admin
   Method : login
