### ISSUE TITLE
Model and Repository classes

### ISSUE THREAD

**Issue by MarvinLeRouge** [MarvinLeRouge/simplimmo#5]

**Comment by MarsaColombo** [comment]
- [ ] Property Model 
- [ ] House Model
- [ ] Appartment model

- [ ] Geo Department
- [ ] Geo Township
- [ ] Geo Region

- [ ] User Model
- [ ] Client Model 
- [ ] Admin model

- [ ] Favorites
- [ ] AsksContacts
